### ISSUE TITLE
Ditch XUL for HTML5 + Electron/NW.js

### ISSUE THREAD

**Issue by Ed-Fernando** [prikhi/pencil#810] opened 2016-03-18 05:15 UTC
In the year 2016 XUL's future is [murky](https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/). Between Mozilla experimenting with Servo + browser.html (servo aims to [implement](https://blogs.s-osg.org/servo-the-embeddable-browser-engine/) the [CEF](https://bitbucket.org/chromiumembedded/cef) API), the rise of HTML5 as a credible standard for the development of rich interfaces and the emergence of Chrome/Chromium as stiff competition to Firefox, it perhaps may be worthwhile to consider moving away from XUL. 

A few advantages of HTML5 I can think of right-off-the-bat are :  (a) Pencil can now be made into an add-on for pretty much every desktop browser that is worth it's salt, yes, even the abomination called Edge. Another platform would be Chrome OS, especially if kids could be taught app development in school, why not provide a fun, interactive tool to do so! (b) The desktop would get love too, just like XUL, if the app can be implemented on top of [Electron](http://electron.atom.io/) or [NW.js](http://nwjs.io/). It would get support for all the three major development platforms by default. (c) Pencil could also end up as a mobile/tablet app. Though web apps on mobile don't have the best reputation, it is an interesting space to experiment with considering all the promising new web frameworks being developed specifically for mobile. (d) ...and other tertiary things like beautiful CSS based themes etc.

I understand that the priority of the project is to get the existing bugs fixed and get to a point of stability and appreciate the effort taken on here. I originally wanted to attempt this myself a couple of years ago but I'm glad that you're walking the path. At the risk of getting ahead of myself I hope you do consider HTML5.

**Comment by mike-auto-mprt** [comment] 2016-03-19 22:36
Once upon a time Dương Thành An who is, I understand, the original author of [pencil made a comment that it had been ported to webkit](https://twitter.com/dgthanhan).  I wonder if that code ever escaped to the wild?  It might be useful in an aim to free Pencil for the web. 

I think that maybe #789 should be done as a first priority?

**Comment by Ed-Fernando** [comment] 2016-03-20 06:52
Whoa! [This](https://twitter.com/dgthanhan/status/698500135983054848) stuff is huge. Version 3? Public beta? For real? These are barely months ago. The dev(s) is(are) even [using Electron for the port](https://twitter.com/dgthanhan/status/685347500727783425) :loudspeaker:

**Comment by bitzl** [comment] 2016-03-20 10:09
I've contacted Dương Thành An via Twitter to ask for details on his work on the port (e.g. if the source is somewhere public).

**Comment by mike-auto-mprt** [comment] 2016-03-20 10:38
@bitzl did you contact him on email?  Before I have tried to contact Evolus, which I think is basically his personal company, but haven't ever got a response.   I have found his email address if needed, but don't want to spam him with another request if you already sent one there.

**Comment by bitzl** [comment] 2016-03-20 11:18
@mike-auto-mprt No, I've responded to his [Twitter post](https://twitter.com/dgthanhan/status/698500135983054848).

**Comment by prikhi** [comment] 2016-03-20 16:43
Wow, didn't even know about Pencil v3. That's great because I have nowhere near the amount of free time it would take to get Pencil from XUL to Webextensions. My last ditch "keep Pencil alive" plan was going to be switching to supporting [Pale Moon](https://www.palemoon.org).

I did try to contact them via Twitter & Email when I forked Pencil, & never got a response. Then I got an email from them saying they were going to bring it back & incorporate some of my changes - but I never heard back from them after that.

**Comment by bitzl** [comment] 2016-03-22 20:04
Got an answer from Dương Thành An:

https://twitter.com/dgthanhan/status/712204376270512128

Seems like he (or he and his team) are working more or less silently on the project and don't plan to show anything before they're done. I've pointed him to this project.

**Comment by ajsb85** [comment] 2016-04-03 00:06
Mozilla going to deprecate XPCOM and XUL for addons. 
Firefox, Thunderbird, Nightingale, Instantbird, Komodo need XUL and XPCOM to work.
The deprecation is for add-ons no for apps...

**Comment by mikedlr** [comment] 2016-04-10 18:17
@prikhi (n.b. this is the same mikedlr - the other account is for automation) 

I think that even with this news it's worth going ahead with setting up a community support system for a version of pencil.  A number of reasons
1. Dương Thành An is clearly not able to respond much.  Having a community which can look after users will always be valuable
2. The current Pencil works now.  It would be useful to allow those that use it for work to migrate off slowly and in a controlled way to any new version
3. If something goes wrong with the new version (e.g. it never becomes available) then it would be really useful to have a head start in maintaining the old one.  

Do you agree?  Would you set up (or like me to set up) a public project?  If you don't have time to or don't want to do it yourself I'll do it (for you) and can give you the right to the repos.

**Comment by Ed-Fernando** [comment] 2016-04-10 19:26
I think we can all agree that the initiative to maintain and enhance an unmaintained codebase is reason enough to applaud the efforts taken here. I also think it might be for the better to put on hold any radical departure like the subject of this feature request so we can wait and watch the lead up to version 3. Perhaps this issue should be closed for now and Pencil can continue receiving love as before? So, all in all, I wish well for v2.1.0! :smile:

**Comment by mikedlr** [comment] 2016-04-10 20:55
@Ed-Fernando 

The major worry is that [xulrunner has been depreciated](https://groups.google.com/forum/?_escaped_fragment_=msg/mozilla.dev.platform/_rFMunG2Bgw/C-4PcHj9IgAJ#!msg/mozilla.dev.platform/_rFMunG2Bgw/C-4PcHj9IgAJ).  
- There's no guarantee how much longer it will be working and/or supported (though I guess Ubuntu 16's recent release including a version gives it a reasonably long lifetime??).  
- There's also no guarantee when the next version of pencil will come out.  It's been two years, and whilst there seems to be some progress there's certainly no deadline given
- Palemoon is likely not to be completely safe since the also [have to update to match firefox](http://www.i-programmer.info/news/86-browsers/9558-pale-moon-highlight-problems-with-following-firefox.html)
- Any migration to another platform might take a very long time. 

So my proposal would be to
- concentrate on stability / bug fixing
- maintain both backwards and forwards file format compatibility (e.g. keep the file format stable)
- hope to maintain the current runner interfaces for a year or more

But even so we shouldn't assume the new software will come out and save us.  That means start gently trying to port to some other javascript / HTML5 engine.  The question is, which?  

I think it might be worth investigating [ionic ](http://ionicframework.com/) as a target?  That would hopefully mean that some of the work done would still be useful even if the new version came out soon.

**Comment by ajsb85** [comment] 2016-04-10 22:42
Positron is the new project of @Mozilla for Run App with Gecko and Spidermonkey
https://github.com/mozilla/positron/tree/master/positron/

**Comment by Ed-Fernando** [comment] 2016-04-11 06:00
@mikedlr 

I concur with all of your proposals, they seem pretty realistic to me. That said, porting to HTML5 is pretty heavy work that I guess most here don't have the time for. I'm a noob coder and have university stuff tying my hands for the next couple of months. I think @prikhi made it pretty clear that he would welcome any contribution in this regard. As for using frameworks, I'm all for them. Ionic + Angular 2 would be awesome. I've even seen websites and mobile apps share the same Ionic code, though I've also seen communities reluctant to bring in third party framework dependencies. 

@ajsb85 

I put no stock in XUL mate. The pace at which Servo and Rust are maturing, it is pretty clear that XUL is not the future. Also, in the future am sure Electron would have support to alternate between Servo and Blink. Positron eh? This is why I love open source software...The possibilities are endless! :smiley:

**Comment by kay1234** [comment] 2016-05-11 14:20
Pencil V3 Preview has been released: [http://pencil.evolus.vn/Next.html](http://pencil.evolus.vn/Next.html)

**Comment by bitzl** [comment] 2016-05-11 14:30
Source code is here: https://gitlab.com/evolus/pencil

2016-05-11 16:20 GMT+02:00 kay1234 notifications@github.com:

**Comment by Craig-Fisk** [comment] 2016-05-11 15:30
Good start, It won't even build for me.

**Comment by mikedlr** [comment] 2016-05-11 15:56
This is great news.  We probably need to concentrate on
- forward porting any changes and/or fixes already made 
- testing backwards compatibility
- regression testing 
- checking / updating instructions for build and so on

**Comment by mikedlr** [comment] 2016-05-11 17:19
I had a mail from Duong Thanh An,  he says that
- the new version aims to support all existing features
- XUL is clearly deprecated 

So probably we would soon announce what the future migration path will be.
-  the new version uses electron.  Who does that mean is left behind?

**Comment by Ed-Fernando** [comment] 2016-05-12 06:57
This has been sooner than most anticipated am sure. Well, finally, we can put all doubts to rest about the project's state. The project page is pretty forthcoming about accommodating potential contributors. While, it makes sense to maintain v2, I would second @mikedlr's thoughts. It is also a no-brainer that new features are better focused on v3. A good place to start would be to setup a mirror of v3, here, on Github for greater visibility. Electron runs pretty much everywhere Chromium runs so right off the bat we have support for Linux (other *nixes too), Mac OS X & Windows. The only people (I wonder) who may have been left behind are those with Windows XP and Vista, as Chrome/Chromium recently [ended support for those](https://chrome.googleblog.com/2015/11/updates-to-chrome-platform-support.html). I am speculating here but in such a scenario would [Positron](https://github.com/mozilla/positron) be a possible replacement for Electron? It would all depend on the demand there is for support for XP and Vista I guess.

**Comment by prikhi** [comment] 2016-05-12 10:52
Got an email about this as well. I was able to open my `.ep` files from Pencil v2 but couldn't add new stencils to my document :/

I'm going to see if Dương is willing to put up a project roadmap along with some issues so we can have some easy ways to hook into the new development.

I think the future of this repo will be patching it to work with Pale Moon(even if they re-fork they said it will still support XUL) & releasing a linux version with a bundled xulrunner(like the windows & os x versions), just to make it last for people who can't switch to v3 for whatever reason.

**Comment by mikedlr** [comment] 2016-05-13 22:22
I'm a bit reluctant to ask too much work from Duong Thanh An.  It's clear from his slow mail responses that he doesn't have much spare time.  There's already an issue tracker at

 https://gitlab.com/evolus/pencil/issues

What could probably be valuable would be going through old, still open issues and:
- if the issue doesn't exist any more, make the note that it's fixed in the new version;  
- close it with won't fix here if we don't think it's realistic to backport the fix
- if the issue still exists create a new issue in gitlab 
- add links in both directions between the issues

then, of course, start trying to fix the bugs, but aim first for fixing the new version.

**Comment by Timmmm** [comment] 2016-06-04 16:14
Released: http://pencil.evolus.vn/Next.html

Worth adding a link to the Readme of this project. Or just redirecting...

**Comment by prikhi** [comment] 2016-11-25 21:56
There's a link to the new project in the readme, I will be keeping this project minimally-maintained for use w/ xulrunner/palemoon.

**Closed as completed by prikhi** 2016-11-25 21:56 UTC
Labels: Priority-Critical
