### ISSUE TITLE
Data Loss (Desktop)

### ISSUE THREAD

**Issue by prikhi** [prikhi/pencil#576] opened 2015-03-13 19:18 UTC
_From [wallfo...@gmail.com](https://code.google.com/u/107931395449472922561/) on July 16, 2013 10:58:11_

What steps will reproduce the problem? 1. Document > Export Document > Export to PDF > All Pages in the document
2. In the Destination field I pasted 
   C:\Documents and Settings\username\Desktop\Test What is the expected output? What do you see instead? 1. Expected output was PDF File. A PDF file didn't get created.
2. Instead all the files inside the folder "Test" got deleted. What version of the product are you using? On what operating system? Version: 2.0.3
Operating System: Windows XP Professional (SP 3) Please provide any additional information below. How do i recover my files which got deleted?

_Original issue: http://code.google.com/p/evoluspencil/issues/detail?id=576_

**Comment by prikhi** [comment] 2015-03-13 19:18
_From [heather_...@trekbikes.com](https://code.google.com/u/106844658307481564367/) on April 10, 2014 13:25:58_

I am using a mac OS X 10.8.5 and just had this same thing happen to me. The folder that ended up disappearing was located on my hard drive in my documents folder (not on my desktop).

**Comment by prikhi** [comment] 2015-03-13 19:18
_From [wallfo...@gmail.com](https://code.google.com/u/107931395449472922561/) on April 10, 2014 23:04:08_

Were you able to resolve it?

**Comment by jdittrich** [comment] 2015-06-02 12:41
Could **not** reproduce bug on:
Ubuntu 14.04.2; Pencil 2.0.10 as Addon in Firefox 38;

However I got a "Not template for exporting to text documents installed" Error message. Not PDF was created.

**Comment by prikhi** [comment] 2015-06-02 13:06
The no template error should be fixed in v2.0.11.

I tried this on a xulrunner build on Linux & was able to reproduce it. 

It looks like Pencil is writing the PDF file over the folder. It should check to see if the path is a folder & either raise an error or append a `.pdf` extension to the path. If the path is an existing file, it should ask the user if it should overwrite it.

**Comment by joemirizio** [comment] 2015-08-02 05:06
I believe this is a duplicate of #459

**Closed as completed** 2015-09-21 09:15 UTC
Labels: bug, imported, 2–5 stars, Priority-Critical, confirmed
