### ISSUE TITLE
Cannot drag items from collections to a page in Firefox on Windows

### ISSUE THREAD

**Issue by alexepshteyn** [prikhi/pencil#825] opened 2016-04-24 19:06 UTC
Pencil 2.0.18
Firefox 45.0.2

when i drag an item from a collection to the page, cursor just shows "do not drop" shape

**Comment by nospamefe** [comment] 2016-05-01 16:09
Same issue here 
Firefos 46.0
Pencil 2.0.18.20160314

Thx !

**Comment by knightsream** [comment] 2016-05-11 02:04
Same here.. Just installed the apps and can't drag anyting. :(

**Comment by lofidevops** [comment] 2016-05-25 11:37
<img width="959" alt="pencil-drag-and-drop-fails" src="https://cloud.githubusercontent.com/assets/229415/15538606/92549e52-227d-11e6-8bf9-f687f0533d68.png">

Windows 7 SP1 / Firefox 46.0.1 / Pencil 2.0.18.20160314

Does anybody on Windows _not_ get this?

**Comment by lofidevops** [comment] 2016-05-25 11:39
It seems that this is not Windows-specific: https://github.com/prikhi/pencil/issues/822

**Comment by lofidevops** [comment] 2016-05-25 11:40
Seems this is a duplicate of https://github.com/prikhi/pencil/issues/802

**Comment by prikhi** [comment] 2016-11-20 18:04
See #802

**Closed as completed by prikhi** 2016-11-20 18:04 UTC
