### ISSUE TITLE
[ Not working ] Can not drag collections to new page

### ISSUE THREAD

**Issue by xros** [prikhi/pencil#822] opened 2016-04-05 02:00 UTC
![snapshot252](https://cloud.githubusercontent.com/assets/2342412/14269140/791e6368-fb14-11e5-84e4-bbbdd187a3c8.png)

os: ubuntu 14.04 amd64
firefox: 45.0
pencil: 2.0.18

P.S. My firefox browser icon was changed to be the one of Pencil, forever!! This should not be.
plugin installed from mozilla addon store.

Pencil looks so awesome, and I do really want to have fun with it.

Don't know if others have the same issue. Hope it can be fixed. Thanks!

**Comment by fschrofner** [comment] 2016-04-06 20:39
I have the same issue using the Firefox version. Works fine with the version provided by pacman (Arch Linux).

**Comment by rizkytahara** [comment] 2016-04-17 23:11
Also have the same problem here with:

OS: Fedora 22
Firefox: 45
Pencil: 2.0.18

There is nothing on the page when I'm dragging the collections object to the page (the page still blank without any object on it).. Any Idea ?

**Comment by BrianMinister** [comment] 2016-04-22 18:20
Also failing here. 
FF 45.0.2, 
Pencil 2.0.18.20160314

**Comment by lofidevops** [comment] 2016-05-25 11:41
Seems this is a duplicate of https://github.com/prikhi/pencil/issues/802

**Comment by xros** [comment] 2016-05-25 17:25
@kwill  This one is firstly reported on Apr 5 2016. Many users had experienced this bug without a fix yet... :crying_cat_face:

**Comment by oDoraemon** [comment] 2016-08-08 06:51
FF 48.0, 
Pencil 2.0.18.20160314
;(

**Comment by dapidc** [comment] 2016-10-04 05:12
Wow... I thought I made mistake somewhere... Looks like it is common issue.

I have same issue on Windows and Ubuntu. FF49. Pencil 2.0.18.20160314

**Comment by jacobbogers** [comment] 2016-10-16 18:41
yeah, same here, it has been some time now, why is this still a problem?

**Comment by armangithub** [comment] 2016-11-10 19:52
I have the same issue running the latest version (v3.0.0-rc.1 branch).

The issue is not replicable dragging a    custom item in the firefox plugin version.

**Comment by prikhi** [comment] 2016-11-20 18:07
See #802

**Closed as completed by prikhi** 2016-11-20 18:07 UTC
